"use client";

import { asset } from "../../lib/cdn";
/**
 * About us — static legal hub matching product screenshots.
 * Banner: /assets/png/aboutBg-2e4b25ca.png
 */

import React, { useState } from "react";
import Image from "next/image";
import { useTranslation } from "react-i18next";
import { IoChevronForward } from "react-icons/io5";
import PageHeader from "../ui/PageHeader";

interface Props {
  onBack: () => void;
}

type SubView = "main" | "confidentiality" | "risk";

const BANNER = asset("/assets/png/aboutBg-2e4b25ca.png");

type DocBlock =
  | { t: "h"; text: string }
  | { t: "p"; text: string }
  | { t: "li"; text: string };

const CONFIDENTIALITY: DocBlock[] = [
  {
    t: "p",
    text: "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
  },
  { t: "h", text: "Interpretation and Definitions" },
  { t: "h", text: "Interpretation" },
  {
    t: "p",
    text: "The words of which the initial letter is capitalized have meanings defined under the following conditions.",
  },
  {
    t: "p",
    text: "The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
  },
  { t: "h", text: "Definitions" },
  {
    t: "p",
    text: "For the purposes of this Privacy Policy:",
  },
  {
    t: "p",
    text: 'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
  },
  {
    t: "p",
    text: 'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BCWIN.',
  },
  {
    t: "p",
    text: 'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
  },
  {
    t: "p",
    text: "Account means a unique account created for You to access our Service or parts of our Service.",
  },
  {
    t: "p",
    text: "Website refers to BCWIN, accessible from BCWIN.",
  },
  { t: "p", text: "Service refers to the Website." },
  { t: "p", text: "Country refers to: United States." },
  {
    t: "p",
    text: "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
  },
  {
    t: "p",
    text: "Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.",
  },
  {
    t: "p",
    text: "Personal Data is any information that relates to an identified or identifiable individual.",
  },
  {
    t: "p",
    text: "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
  },
  {
    t: "p",
    text: "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
  },
  {
    t: "p",
    text: "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  { t: "h", text: "Collecting and Using Your Personal Data" },
  { t: "h", text: "Types of Data Collected" },
  { t: "h", text: "Personal Data" },
  {
    t: "p",
    text: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
  },
  { t: "li", text: "Email address" },
  { t: "li", text: "First name and last name" },
  { t: "li", text: "Phone number" },
  { t: "li", text: "Address, State, Province, ZIP/Postal code, City" },
  { t: "li", text: "Usage Data" },
  { t: "h", text: "Usage Data" },
  {
    t: "p",
    text: "Usage Data is collected automatically when using the Service.",
  },
  {
    t: "p",
    text: "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
  },
  {
    t: "p",
    text: "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
  },
  {
    t: "p",
    text: "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.",
  },
  { t: "h", text: "Tracking Technologies and Cookies" },
  {
    t: "p",
    text: "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.",
  },
  {
    t: "p",
    text: "You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.",
  },
  {
    t: "p",
    text: 'Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.',
  },
  {
    t: "p",
    text: "We use both session and persistent Cookies for the purposes set out below:",
  },
  { t: "h", text: "Necessary / Essential Cookies" },
  { t: "p", text: "Type: Session Cookies" },
  { t: "p", text: "Administered by: Us" },
  {
    t: "p",
    text: "Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.",
  },
  { t: "h", text: "Cookies Policy / Notice Acceptance Cookies" },
  { t: "p", text: "Type: Persistent Cookies" },
  { t: "p", text: "Administered by: Us" },
  {
    t: "p",
    text: "Purpose: These Cookies identify if users have accepted the use of cookies on the Website.",
  },
  { t: "h", text: "Functionality Cookies" },
  { t: "p", text: "Type: Persistent Cookies" },
  { t: "p", text: "Administered by: Us" },
  {
    t: "p",
    text: "Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.",
  },
  {
    t: "p",
    text: "For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy.",
  },
  { t: "h", text: "Use of Your Personal Data" },
  {
    t: "p",
    text: "The Company may use Personal Data for the following purposes:",
  },
  {
    t: "li",
    text: "To provide and maintain our Service, including to monitor the usage of our Service.",
  },
  {
    t: "li",
    text: "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
  },
  {
    t: "li",
    text: "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
  },
  {
    t: "li",
    text: "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
  },
  {
    t: "li",
    text: "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
  },
  {
    t: "li",
    text: "To manage Your requests: To attend and manage Your requests to Us.",
  },
  {
    t: "p",
    text: "We may share your personal information in the following situations:",
  },
  {
    t: "li",
    text: "With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.",
  },
  {
    t: "li",
    text: "For Business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.",
  },
  {
    t: "li",
    text: "With Affiliates: We may share your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.",
  },
  {
    t: "li",
    text: "With Business partners: We may share your information with Our business partners to offer You certain products, services or promotions.",
  },
  {
    t: "li",
    text: "With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.",
  },
  { t: "h", text: "Retention of Your Personal Data" },
  {
    t: "p",
    text: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
  },
  {
    t: "p",
    text: "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
  },
  { t: "h", text: "Transfer of Your Personal Data" },
  {
    t: "p",
    text: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
  },
  {
    t: "p",
    text: "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
  },
  {
    t: "p",
    text: "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
  },
  { t: "h", text: "Disclosure of Your Personal Data" },
  { t: "h", text: "Business Transactions" },
  {
    t: "p",
    text: "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
  },
  { t: "h", text: "Law enforcement" },
  {
    t: "p",
    text: "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
  },
  { t: "h", text: "Other legal requirements" },
  {
    t: "p",
    text: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
  },
  { t: "li", text: "Comply with a legal obligation" },
  { t: "li", text: "Protect and defend the rights or property of the Company" },
  {
    t: "li",
    text: "Prevent or investigate possible wrongdoing in connection with the Service",
  },
  {
    t: "li",
    text: "Protect the personal safety of Users of the Service or the public",
  },
  { t: "li", text: "Protect against legal liability" },
  { t: "h", text: "Security of Your Personal Data" },
  {
    t: "p",
    text: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
  },
  { t: "h", text: "Children's Privacy" },
  {
    t: "p",
    text: "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
  },
  {
    t: "p",
    text: "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
  },
  { t: "h", text: "Links to Other Websites" },
  {
    t: "p",
    text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
  },
  {
    t: "p",
    text: "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
  },
  { t: "h", text: "Changes to this Privacy Policy" },
  {
    t: "p",
    text: 'We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.',
  },
  {
    t: "p",
    text: 'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.',
  },
  {
    t: "p",
    text: "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
  },
  { t: "h", text: "Contact Us" },
  {
    t: "p",
    text: "If you have any questions about this Privacy Policy, You can contact us:",
  },
  {
    t: "p",
    text: "By visiting this page on our website: BCWIN",
  },
];

const RISK_DISCLOSURE: DocBlock[] = [
  {
    t: "p",
    text: "To prevent disputes during gaming, please carefully read this User Risk Disclosure Agreement before participating. By participating, you confirm that you have fully understood and accepted all terms and conditions of this agreement.",
  },
  {
    t: "p",
    text: "1. In order to avoid disputes related to user accounts, users must carefully read this risk disclosure agreement before opening an account. Once users open an account, it will be deemed that users have fully understood and agreed to the following terms and conditions of this risk disclosure agreement.",
  },
  {
    t: "p",
    text: "2. Users should have full civil capacity and the capacity to bear legal responsibilities. If a user is not a natural person with full civil capacity and civil rights capacity, the user and their guardian shall bear all consequences arising therefrom, and our company shall not be held liable.",
  },
  {
    t: "p",
    text: "3. Users should carefully review their local laws and regulations regarding online gaming. If online gaming is prohibited in the user's region, the user will be solely responsible for any legal liability arising from their participation.",
  },
  {
    t: "p",
    text: "4. Users should carefully review the website content and utilize free trial functions before engaging in real-money gaming. Users must carefully consider their financial situation and risk tolerance before deciding to participate. Users should be fully aware that online gaming involves risks and potential losses. If users cannot accept these risks, they should not participate.",
  },
  {
    t: "p",
    text: "5. Users are solely responsible for the security of their own accounts. Users must carefully safeguard their account passwords and other security information. All consequences arising from account password leakage due to the user's own reasons shall be borne by the user. Our company shall not be held liable for any losses caused by third-party account theft or other security issues.",
  },
];

export default function AboutUsPage({ onBack }: Props) {
  const { t } = useTranslation();
  const [view, setView] = useState<SubView>("main");

  if (view === "confidentiality") {
    return (
      <LegalDoc
        title={t("about.confidentiality")}
        blocks={CONFIDENTIALITY}
        onBack={() => setView("main")}
      />
    );
  }

  if (view === "risk") {
    return (
      <LegalDoc
        title={t("about.riskDisclosure")}
        blocks={RISK_DISCLOSURE}
        onBack={() => setView("main")}
      />
    );
  }

  return (
    <div
      className="flex flex-col min-h-screen min-w-0 w-full max-w-full overflow-x-clip pb-[max(2.5rem,env(safe-area-inset-bottom))]"
      style={{ background: "#110D14" }}
    >
      <PageHeader title={t("about.title")} onBack={onBack} />

      {/* Design banner */}
      <div className="relative w-full overflow-hidden" style={{ aspectRatio: "750 / 284" }}>
        <Image
          src={BANNER}
          alt=""
          fill
          priority
          sizes="(max-width: 480px) 100vw, 480px"
          className="object-cover object-center"
        />
      </div>

      {/* Menu list — matches screenshot: gold icons + labels on dark body */}
      <div className="px-4 pt-1">
        <AboutRow
          icon={<DocIcon />}
          label={t("about.confidentiality")}
          onClick={() => setView("confidentiality")}
        />
        <div className="h-px" style={{ background: "rgba(255,255,255,0.06)" }} />
        <AboutRow
          icon={<BookmarkIcon />}
          label={t("about.riskDisclosure")}
          onClick={() => setView("risk")}
        />
      </div>
    </div>
  );
}

function LegalDoc({
  title,
  blocks,
  onBack,
}: {
  title: string;
  blocks: readonly DocBlock[];
  onBack: () => void;
}) {
  return (
    <div
      className="flex flex-col min-h-screen min-w-0 w-full max-w-full overflow-x-clip pb-[max(2.5rem,env(safe-area-inset-bottom))]"
      style={{ background: "#110D14" }}
    >
      <PageHeader title={title} onBack={onBack} />
      <div className="px-4 pt-3 pb-8 space-y-3">
        {blocks.map((b, i) => {
          if (b.t === "h") {
            return (
              <h2
                key={i}
                className="pt-1 text-[15.5px] sm:text-[16px] font-bold text-[#FDE4BC] leading-snug"
              >
                {b.text}
              </h2>
            );
          }
          if (b.t === "li") {
            return (
              <p
                key={i}
                className="pl-3 text-[14.5px] sm:text-[15px] leading-[1.65] text-white/65 font-medium"
              >
                • {b.text}
              </p>
            );
          }
          return (
            <p
              key={i}
              className="text-[14.5px] sm:text-[15px] leading-[1.65] text-white/65 font-medium"
            >
              {b.text}
            </p>
          );
        })}
      </div>
    </div>
  );
}

function AboutRow({
  icon,
  label,
  onClick,
}: {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="w-full flex items-center gap-3 py-4 active:opacity-75 min-w-0"
    >
      <span className="shrink-0 w-7 h-7 flex items-center justify-center" aria-hidden>
        {icon}
      </span>
      <span className="flex-1 text-left text-[16px] font-semibold text-[#FDE4BC] truncate">
        {label}
      </span>
      <IoChevronForward size={18} className="text-[#FED358] shrink-0 opacity-90" />
    </button>
  );
}

/** Gold document / list icon (screenshot left of Confidentiality) */
function DocIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M7 3.5h7.2L19 8.2V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 6 20V5A1.5 1.5 0 0 1 7.5 3.5H7z"
        stroke="#FED358"
        strokeWidth="1.7"
        strokeLinejoin="round"
      />
      <path d="M14 3.5V8h5" stroke="#FED358" strokeWidth="1.7" strokeLinejoin="round" />
      <path
        d="M9 12h6M9 15.5h6"
        stroke="#FED358"
        strokeWidth="1.7"
        strokeLinecap="round"
      />
    </svg>
  );
}

/** Gold bookmark icon (screenshot left of Risk Disclosure) */
function BookmarkIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M7 4.5h10A1.5 1.5 0 0 1 18.5 6v14.2l-6.5-3.6-6.5 3.6V6A1.5 1.5 0 0 1 7 4.5z"
        stroke="#FED358"
        strokeWidth="1.7"
        strokeLinejoin="round"
      />
    </svg>
  );
}
